### ISSUE TITLE
Error when converting gtfs.zip to postgresDB

### ISSUE THREAD

**Issue by kdheepak** [jarondl/pygtfs#31] opened 2016-07-10 09:38 UTC
I get the following error when running `gtfs2db` script

> gtfs2db append gtfs.zip postgresql://localhost/gtfs_db

```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) there is no unique constraint matching given keys for referenced table "stops"
 [SQL: '\nCREATE TABLE translations (\n\tfeed_id INTEGER, \n\ttrans_id VARCHAR NOT NULL, \n\tlang VARCHAR NOT NULL, \n\ttranslation VARCHAR, \n\tPRIMARY KEY (trans_id, lang), \n\tFOREIGN KEY(feed_id, trans_id) REFERENCES stops (feed_id, stop_name), \n\tFOREIGN KEY(feed_id) REFERENCES _feed (feed_id)\n)\n\n']
```

Any idea what the problem might be?

**Comment by KAMI911** [comment] 2017-11-08 19:29
Hi it seems I hit same error, while SQLight works. Using virtualenv, Python 3.5, I got this error:

bin/python bin/gtfs2db append /common/mav/ postgresql://data:fata@localhost:5432
Traceback (most recent call last):
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
psycopg2.ProgrammingError: there is no unique constraint matching given keys for referenced table "stops"


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bin/gtfs2db", line 11, in <module>
    sys.exit(main())
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/pygtfs/gtfs2db.py", line 51, in main
    schedule = Schedule(args['<database>'])
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/pygtfs/schedule.py", line 38, in __init__
    Base.metadata.create_all(self.engine)
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/sql/schema.py", line 3949, in create_all
    tables=tables)
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1929, in _run_visitor
    conn._run_visitor(visitorcallable, element, **kwargs)
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1538, in _run_visitor
    **kwargs).traverse_single(element)
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/sql/ddl.py", line 733, in visit_metadata
    _is_metadata_operation=True)
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/sql/visitors.py", line 121, in traverse_single
    return meth(obj, **kw)
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/sql/ddl.py", line 767, in visit_table
    include_foreign_key_constraints=include_foreign_key_constraints
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/sql/ddl.py", line 68, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1002, in _execute_ddl
    compiled
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/common/python/gtfsdb-py35/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) there is no unique constraint matching given keys for referenced table "stops"
 [SQL: '\nCREATE TABLE translations (\n\tfeed_id INTEGER, \n\ttrans_id VARCHAR NOT NULL, \n\tlang VARCHAR NOT NULL, \n\ttranslation VARCHAR, \n\tPRIMARY KEY (trans_id, lang), \n\tFOREIGN KEY(feed_id, trans_id) REFERENCES stops (feed_id, stop_name), \n\tFOREIGN KEY(feed_id) REFERENCES _feed (feed_id)\n)\n\n']

**Comment by jarondl** [comment] 2018-11-11 20:54
I know this is rather old, but does someone have an example of a gtfs file that fails with the most recent 0.1.4 release?

**Comment by jarondl** [comment] 2018-11-14 02:19
I'm closing this for now, since I don't have a reproducible testcase, and I suspect this was fixed by #44. Please feel free to reopen if this still exists.

**Comment by chimo** [comment] 2018-12-11 00:21
I'm getting the same error with:
* virtualenv v16.0.0
* Python v3.7.1
* postgresql v11.1
* psycopg2 v2.7.6.1
* pygtfs @ d3b4727d8475b68b8ad41eb32ab26f0ce458c390
* The following gtfs zip: http://www.octranspo1.com/files/google_transit.zip

**Comment by jarondl** [comment] 2018-12-17 03:19
OK, so this is a legitimate error, for all databases, not just postgresql.
Translations uses stop_name for the relationship, but nothing guarantees it to be unique.
This was probably introduced in #17 and somehow only postgresql complains, but all databases should have a problem with it.

**Comment by jarondl** [comment] 2019-02-02 02:32
This should be fixed in master right now.

**Comment by chimo** [comment] 2019-02-04 03:44
Yep, works for me. Thanks!

**Comment by jarondl** [comment] 2023-01-31 16:19
Yep.

**Closed by jarondl** 2023-01-31 16:19 UTC
